project_id: datcom-apigee-dev
proxies:
  - name: api
    policies:
      - am-disable-compression
      - copy-key-param-to-header
      - verify-api-key-in-header
      - rewrite-missing-key-message
      - rewrite-missing-allow-header-error
      - enforce-quota-limit
      - rewrite-quota-exceeded-message
      - set-southbound-key
      - strip-api-key-header-and-params
      - block-internal-only-endpoints
      - block-deprecated-endpoints
    proxy_endpoints:
      - api
    target_endpoints:
      - api
      - mcp
  - name: nl
    policies:
      - copy-key-param-to-header
      - verify-api-key-in-header
      - strip-api-key-header-and-params
    proxy_endpoints:
      - nl
    target_endpoints:
      - nl
