project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2026_02_12_02_37_23
  - auto1w_2026_02_12_11_48_18
  - auto2w_2026_02_09_15_48_32
  - biomedical_2026_01_02_03_45_47
  - country_2026_02_12_10_21_59
  - disaster_2026_02_08_21_26_52
  - frequent_2026_02_12_06_35_48
  - infrequent_2026_02_05_04_21_59
  - ipcc_2026_01_02_03_42_44
  - place_2026_02_10_00_57_53
  - schema_2026_02_12_12_15_45
  - uscensus_2026_02_07_03_44_20
