project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2024_02_12_02_17_12
  - auto1w_2024_02_12_14_06_58
  - auto2w_2024_02_06_09_41_11
  - biomedical_2024_01_24_15_00_29
  - country_2024_02_12_10_22_40
  - disaster_2024_02_11_21_32_55
  - frequent_2024_02_13_09_01_58
  - infrequent_2024_02_12_11_40_19
  - ipcc_2024_02_01_03_52_19
  - place_2024_02_03_03_49_40
  - schema_2024_02_13_00_21_06
