project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2026_01_28_02_20_59
  - auto1w_2026_01_27_09_50_25
  - auto2w_2026_01_27_23_34_23
  - biomedical_2026_01_02_03_45_47
  - country_2026_01_27_10_18_58
  - disaster_2026_01_25_21_28_29
  - frequent_2026_01_27_05_25_24
  - infrequent_2026_01_27_09_47_26
  - ipcc_2026_01_02_03_42_44
  - place_2026_01_05_03_28_18
  - schema_2026_01_28_00_17_31
  - uscensus_2026_01_07_03_46_04
