project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2026_02_08_02_20_15
  - auto1w_2026_02_03_04_04_13
  - auto2w_2026_02_03_03_24_21
  - biomedical_2026_01_02_03_45_47
  - country_2026_02_08_10_12_17
  - disaster_2026_01_25_21_28_29
  - frequent_2026_02_08_05_16_50
  - infrequent_2026_02_05_04_21_59
  - ipcc_2026_01_02_03_42_44
  - place_2026_02_03_04_01_29
  - schema_2026_02_08_18_13_57
  - uscensus_2026_02_07_03_44_20
