project: datcom-store
instance: prophet-cache
tables:
  - frequent_2023_06_03_08_33_20
  - ipcc_2023_06_01_03_50_51
  - biomedical_2023_06_02_03_45_35
  - disaster_2023_06_03_13_08_47
  - infrequent_2023_05_19_10_24_48
  - place_2023_06_03_03_55_29