project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2025_12_03_02_36_23
  - auto1w_2025_11_02_21_01_08
  - auto2w_2025_10_30_05_04_54
  - biomedical_2025_11_24_02_16_31
  - country_2025_12_03_10_19_40
  - disaster_2025_11_30_21_26_23
  - frequent_2025_12_03_05_13_24
  - infrequent_2025_11_05_03_51_33
  - ipcc_2025_10_03_03_42_10
  - place_2025_12_03_03_56_54
  - schema_2025_12_03_12_14_29
  - uscensus_2025_11_07_16_33_35
