project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2025_11_03_02_17_16
  - auto1w_2025_11_02_21_01_08
  - auto2w_2025_10_30_05_04_54
  - biomedical_2025_10_02_04_07_57
  - country_2025_11_03_10_26_48
  - disaster_2025_11_02_21_30_39
  - frequent_2025_11_03_05_16_09
  - infrequent_2025_10_05_03_42_30
  - ipcc_2025_10_03_03_42_10
  - place_2025_11_03_03_43_56
  - place_2025_11_03_03_43_56
  - uscensus_2025_10_07_03_43_42
