project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2024_10_03_02_18_23
  - auto1w_2024_09_29_21_02_05
  - auto2w_2024_10_01_10_41_33
  - biomedical_2024_10_02_03_47_17
  - country_2024_10_02_10_18_23
  - disaster_2024_09_29_21_31_41
  - frequent_2024_10_02_14_47_25
  - infrequent_2024_09_05_03_47_53
  - ipcc_2024_10_01_10_06_01
  - place_2024_09_03_03_47_44
  - schema_2024_10_03_00_17_46
  - uscensus_2024_09_07_03_46_57
