project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2025_03_04_02_17_08
  - auto1w_2025_03_04_10_24_30
  - auto2w_2025_02_24_10_13_51
  - biomedical_2025_03_02_03_40_59
  - country_2025_03_04_10_19_48
  - disaster_2025_03_02_21_32_50
  - frequent_2025_03_04_05_15_48
  - infrequent_2025_02_05_03_47_15
  - ipcc_2025_03_01_03_44_01
  - place_2025_03_03_03_43_41
  - schema_2025_03_04_18_56_12
  - uscensus_2025_02_07_03_44_40