project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2025_12_10_02_47_01
  - auto1w_2025_12_08_19_33_18
  - auto2w_2025_12_10_00_05_48
  - biomedical_2025_11_24_02_16_31
  - country_2025_12_09_10_20_49
  - disaster_2025_12_07_23_03_14
  - frequent_2025_12_09_05_20_28
  - infrequent_2025_12_05_03_46_14
  - ipcc_2025_10_03_03_42_10
  - place_2025_12_15_19_05_56
  - schema_2025_12_10_06_22_34
  - uscensus_2025_12_07_03_37_42
