project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2026_02_04_02_16_29
  - auto1w_2026_02_03_04_04_13
  - auto2w_2026_02_03_03_24_21
  - biomedical_2026_01_02_03_45_47
  - country_2026_02_04_10_16_32
  - disaster_2026_01_25_21_28_29
  - frequent_2026_02_04_05_14_51
  - infrequent_2026_01_27_09_47_26
  - ipcc_2026_01_02_03_42_44
  - place_2026_02_03_04_01_29
  - schema_2026_02_05_00_13_25
  - uscensus_2026_01_07_03_46_04
