project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2025_12_04_02_18_29
  - auto1w_2025_12_04_08_43_30
  - auto2w_2025_10_30_05_04_54
  - biomedical_2025_11_24_02_16_31
  - country_2025_12_04_10_17_42
  - disaster_2025_11_30_21_26_23
  - frequent_2025_12_04_05_15_28
  - infrequent_2025_12_04_00_47_45
  - ipcc_2025_10_03_03_42_10
  - place_2025_12_03_03_56_54
  - schema_2025_12_04_18_21_42
  - uscensus_2025_11_07_16_33_35
