project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2026_01_13_14_50_19
  - auto1w_2026_01_08_12_02_35
  - auto2w_2026_01_13_09_29_00
  - biomedical_2026_01_02_03_45_47
  - country_2026_01_14_10_23_23
  - disaster_2026_01_11_21_32_15
  - frequent_2026_01_14_05_17_32
  - infrequent_2025_12_15_19_08_30
  - ipcc_2026_01_02_03_42_44
  - place_2025_12_15_19_05_56
  - schema_2026_01_15_00_13_41
  - uscensus_2026_01_07_03_46_04
