project: datcom-store
instance: prophet-cache
tables:
  - auto1d_2026_02_10_02_15_11
  - auto1w_2026_02_03_04_04_13
  - auto2w_2026_02_09_15_48_32
  - biomedical_2026_01_02_03_45_47
  - country_2026_02_09_10_16_19
  - disaster_2026_02_08_21_26_52
  - frequent_2026_02_09_05_18_26
  - infrequent_2026_02_05_04_21_59
  - ipcc_2026_01_02_03_42_44
  - place_2026_02_10_00_57_53
  - schema_2026_02_10_00_13_48
  - uscensus_2026_02_07_03_44_20
