clusters:
  - projects/datcom-mixer-autopush/locations/us-central1/clusters/mixer-us-central1
liveUrl: https://autopush.api.datacommons.org
flags:
  EnableV3: true
  V3MirrorFraction: 0.0
  WriteUsageLogs: 1.0
  UseSpannerGraph: true
  SpannerGraphDatabase: dc_graph_2025_11_07
  UseStaleReads: true
  EnableEmbeddingsResolver: true
