# Flags for mixer bundled with website autopush
clusters:
  - projects/datcom-website-autopush/locations/us-central1/clusters/website-us-central1
liveUrl: https://autopush.datacommons.org
flags:
  EnableV3: true
  V3MirrorFraction: 1.0
  WriteUsageLogs: 1.0
  UseSpannerGraph: true
  SpannerGraphDatabase: dc_graph_2026_01_27
  UseStaleReads: true
