# Flags for mixer bundled with website dev
clusters:
  - projects/datcom-website-dev/locations/us-central1/clusters/website-us-central1
liveUrl: https://dev.datacommons.org
flags:
  EnableV3: true
  V3MirrorFraction: 1.0
  WriteUsageLogs: 1.0
  UseSpannerGraph: true
  SpannerGraphDatabase: dc_graph_2015_10_14
