# Flags for mixer bundled with website staging
clusters:
  - projects/datcom-website-staging/locations/us-central1/clusters/website-us-central1
liveUrl: https://staging.datacommons.org
flags:
  EnableV3: true
  V3MirrorFraction: 1.0
  WriteUsageLogs: 1.0
  UseSpannerGraph: true
  SpannerGraphDatabase: dc_graph_2025_11_07
  UseStaleReads: true
  EnableEmbeddingsResolver: true
