clusters:
  - projects/datcom-mixer-staging/locations/us-central1/clusters/mixer-us-central1
liveUrl: https://staging.api.datacommons.org
flags:
  EnableV3: true
  V3MirrorFraction: 0.0
  WriteUsageLogs: 1.0
  UseSpannerGraph: true
  SpannerGraphDatabase: dc_graph_2015_10_14
